java -jar FPGrowth.jar Mushroom.txt 1.0 > Mushroom/Mushroom_10.txt
java -jar FPGrowth.jar Mushroom.txt 0.9 > Mushroom/Mushroom_9.txt
java -jar FPGrowth.jar Mushroom.txt 0.8 > Mushroom/Mushroom_8.txt
java -jar FPGrowth.jar Mushroom.txt 0.7 > Mushroom/Mushroom_7.txt
java -jar FPGrowth.jar Mushroom.txt 0.6 > Mushroom/Mushroom_6.txt
java -jar FPGrowth.jar Mushroom.txt 0.5 > Mushroom/Mushroom_5.txt
java -jar FPGrowth.jar Mushroom.txt 0.4 > Mushroom/Mushroom_4.txt
java -jar FPGrowth.jar Mushroom.txt 0.3 > Mushroom/Mushroom_3.txt
java -jar FPGrowth.jar Mushroom.txt 0.2 > Mushroom/Mushroom_2.txt
java -jar FPGrowth.jar Mushroom.txt 0.1 > Mushroom/Mushroom_1.txt
